### ISSUE TITLE
Allow promise chaining / forwarding with the guzzle lib

### ISSUE THREAD

**Issue by b3nl** [commercetools/commercetools-php-sdk#274]
If you try to [forward/chain a promise](https://github.com/guzzle/promises#promise-forwarding) containing a response for a resolved async request, the AbstractApiResponse throws a "non future exception". If i work around this and try to use a guzzles FulfilledPromise, guzzle fails with a "new InvalidArgumentException('You cannot create a FulfilledPromise with a promise.');" ... 

Is there any special reason, why you block the chaining with a resolved request? I can not find any sense in it at this moment. If you don't know why aswell, could you please fix it?

(I can not wait for this, so i helped myself with https://github.com/bestit/commercetools-async-pool, but I do not like the style i needed to go.)

**Comment by jayS-de** [comment]
As i wrapped the guzzle client to be able to use Guzzle5 as well as Guzzle6 I also had to wrap the responses. When using the synchronous execution guzzle returns a response object. Using the asynchronous execution you will get back a PSR-7 response instance.

To be able to existing middleware I decided to return on asynchronous execution the PSR-7 response instead of an ApiResponse as it's easy to wrap the guzzle response inside the promise chain like this:

```php
$promise = $this->client->executeAsync($request)
            ->then(
                function (ResponseInterface $response) use ($request) {
                    $apiResponse = $request->buildResponse($response);

                    return $request->mapFromResponse($apiResponse);
                },
                function (RequestException $exception ) {
                    $response = $exception->getResponse();
                    return ApiException::create($exception->getRequest(), $response, $exception);
                }
            )
```

I just opened a pull request to your async pool which makes use of this example.

**Comment by b3nl** [comment]
If you believe it or not, I tried exaktly (but did not use P\settle($this->promises)->wait();) that before I wrote the issue and it failed like I described it in the inline comment and in the issue ... checking your code, it works ... maybe I did run into another side effect ... thx, but then i will add my initial wish first, before merging your pr.
