### ISSUE TITLE
Product Mapping with ProductTypeInformation

### ISSUE THREAD

**Issue by jenschude** [commercetools/commercetools-php-sdk#99]

**Comment by nkuehn** [comment]
short log of @ct-jensschulze and me spoke about last week:  The structure of the PHP API should be cenceptually aligned with the upcoming custom fields feature (which will be on all other API endpoints but products).  This feature will have a reference to the type metadata right next to the data which is expandable via reference expansion. 

So the collection of custom fields has an optional collection of field descriptions.  If these are present, the fields can be mapped cleanly.  
For the custom product attributes (via productType) the type reference is not right next to the attribute values, but top-level on the product object. But the PHP SDK could provide them next to the actual custom attributes so that the upwards path traversal is not as complex to trigger clean typing of the attributes.  

So far so good. We should decide: delay this API until the "new" custom fields are available and create a coherent PHP API?

**Comment by nkuehn** [comment]
@ct-jensschulze  please decide yourself if you want to adress parts of this in RC2 already 1.0.0
